"""
? Django settings for core project.

? Generated by 'django-admin startproject' using Django 3.2.5.

! For more information on this file, see
* https://docs.djangoproject.com/en/3.2/topics/settings/

! For the full list of settings and their values, see
* https://docs.djangoproject.com/en/3.2/ref/settings/
"""


from pathlib import Path
from decouple import config
import os
# ! Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# ? Quick-start development settings - unsuitable for production
# * See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# ! SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY')  # TODO Instead of this place your genereated secret key

# ! SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = [

]

INTERNAL_IPS = [
    '127.0.0.1',
]


# ! Application definition

INSTALLED_APPS = [
    'admin_interface',
    'colorfield',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'debug_toolbar',
    'accounts',
    'widget_tweaks'
]

X_FRAME_OPTIONS = 'SAMEORIGIN'

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'debug_toolbar.middleware.DebugToolbarMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates/'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'

# ! Authentication
# * https://docs.djangoproject.com/en/3.2/topics/auth/default/
AUTH_USER_MODEL = 'accounts.Account'


# ! Database
# * https://docs.djangoproject.com/en/3.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': config('DB_NAME'),  # TODO Instead of this place your db server name
        'USER': config('DB_USER'),  # TODO Instead of this place your db user
        'PASSWORD': config('DB_PASSWORD'),  # TODO Instead of this place your db password
        'HOST': config('DB_HOST')  # TODO Instead of this place your db host
        # ? i.e 'localhost'
    }
}


# ! Password validation
# * https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# ! Internationalization
# * https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# ! Static files (CSS, JavaScript, Images)
# * https://docs.djangoproject.com/en/3.2/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')]

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')


# ! Sending Emails
# * https://docs.djangoproject.com/en/3.2/topics/email/d

# ? Make sure to toogle less secure apps if using gmail
# * https://myaccount.google.com/lesssecureapps

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_USE_TLS = True
EMAIL_PORT = config('EMAIL_PORT')  # TODO Instead of this place your port
# ? i.e EMAIL_PORT = 587        <= This works for gmail
EMAIL_HOST_USER = config('EMAIL_HOST_USER')  # TODO Instead of this place your email
# ? i.e EMAIL_HOST_USER = 'johndoe@example.com'
EMAIL_HOST_PASSWORD = config('EMAIL_HOST_PASSWORD')  # TODO Instead of this place your email's password

# ! Default primary key field type
# * https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
